services:
  mongo:
    image: mongo:7
    container_name: leaveflow-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: leaveflow-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/leaveflow
      - JWT_SECRET=${JWT_SECRET}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: leaveflow-frontend
    restart: unless-stopped
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data: